export const skills = [
  {
    id: "html",
    name: "HTML",
    colors: ["#E34F26", "#7C2D12"],
    emissive: "#38bdf8",
    icon: "/icons/png/html.png",
  },
  {
    id: "css",
    name: "CSS",
    colors: ["#2965F1", "#1E3A8A"],
    icon: "/icons/png/css.png",
  },
  {
    id : "js",
    name: "JavaScript",
    colors: ["#F7DF1E", "#A16207"],
    icon: "/icons/png/js.png",
  },
  {
    id: "react",
    name: "React",
    colors: ["#61DAFB", "#0F172A"],
    icon: "/icons/png/react.png",
  },
  {
    id:"node",
    name: "Node.js",
    colors: ["#3C873A", "#14532D"],
    icon: "/icons/png/node.png",
  },
  {
    id:"nestjs",
    name: "Nest.js",
    colors: ["#E0234E", "#7F1D1D"],
    icon: "/icons/png/nest.png",
  },
  {
    id:"tailwind",
    name: "Tailwind CSS",
    colors: ["#38BDF8", "#0C4A6E"],
    icon: "/icons/png/tailwind.png",
  },
  {
    id:"mysql",
    name: "MySQL",
    colors: ["#00758F", "#0F172A"],
    icon: "/icons/png/mysql.png",
  },
  {
    id:"vercel",
    name: "Vercel",
    colors: ["#fff", "#1F2933"],
    icon: "/icons/png/vercel.png",
  },
  {
    id:"wordpress",
    name: "WordPress",
    colors: ["#21759B", "#0F172A"],
    icon: "/icons/png/wordpress.png",
  },
  {
    id:"git",
    name: "Git",
    colors: ["#F05032", "#7C2D12"],
    icon: "/icons/png/git.png",
  },
  {
    id:"github",
    name: "GitHub",
    colors: ["#fff", "#374151"],
    icon: "/icons/png/github.png",
  },
  {
    id:"express",
    name: "Express",
    colors: ["#F5F5F5", "#111827"],
    icon: "/icons/png/express.png",
  },
  {
    id:"python",
    name: "Python",
    colors: ["#3776AB", "#FFD43B"],
    icon: "/icons/png/python.png",
  },
  {
    id:"ciber",
    name: "Cibersegurança",
    colors: ["#7C3AED", "#1E1B4B"],
    icon: "/icons/png/ciber.png",
  },
  {
    id:"linux",
    name: "Linux",
    colors: ["#FCC624", "#111827"],
    icon: "/icons/png/linux.png",
  },
  {
    id:"redes",
    name: "Redes",
    colors: ["#eee", "#082F49"],
    icon: "/icons/png/redes.png",
  },
  
];
